---
- name: Create instances
  loop: 
    - "{{ osp_servers.frontend }}"
    - "{{ osp_servers.app1 }}"
    - "{{ osp_servers.app2 }}"
    - "{{ osp_servers.db }}"
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group={{ item.meta.group }},deployment_name={{ item.meta.deployment_name }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /etc/yum.repos.d/internal.repo https://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
  
- name: Associate floating IP to instances
  loop:
    - "{{ osp_servers.frontend }}"
    - "{{ osp_servers.app1 }}"
    - "{{ osp_servers.app2 }}"
    - "{{ osp_servers.db }}"
  os_floating_ip:
    cloud: openstack
    state: "{{ item.state }}"
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 200
